//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoundEventsEntities : DbContext
    {
        public SoundEventsEntities()
            : base("name=SoundEventsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SoundEvent> SoundEvents { get; set; }
        public virtual DbSet<SoundLog> SoundLogs { get; set; }
        public virtual DbSet<Sound> Sounds { get; set; }
    }
}
