//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoundEvent
    {
        public int SoundEventID { get; set; }
        public int SoundID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Sound Sound { get; set; }
    }
}
